'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } },
}

const stagger = {
  visible: { transition: { staggerChildren: 0.1 } },
}

// Fake slide mockup card
function SlidePreview() {
  return (
    <div className="relative w-full max-w-xl mx-auto">
      {/* Floating background cards for depth */}
      <div className="absolute -bottom-3 -right-3 w-full h-full bg-indigo-500/10 dark:bg-indigo-900/30 rounded-card" />
      <div className="absolute -bottom-1.5 -right-1.5 w-full h-full bg-indigo-400/10 dark:bg-indigo-800/20 rounded-card" />

      <motion.div
        animate={{ y: [0, -8, 0] }}
        transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
        className="relative bg-dark-bg-surface border border-dark-text-muted/20 rounded-card overflow-hidden shadow-2xl"
      >
        {/* Slide header bar */}
        <div className="h-1.5 bg-accent-primary" />
        <div className="p-6">
          {/* Slide title */}
          <div className="flex items-center gap-3 mb-5">
            <div className="w-8 h-8 rounded bg-accent-primary/20 flex items-center justify-center">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#5B4CF5" strokeWidth="2.5">
                <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>
              </svg>
            </div>
            <div>
              <div className="text-white text-sm font-medium">The Future of Climate Technology</div>
              <div className="text-dark-text-muted text-xs mt-0.5">Generated by DeckIQ</div>
            </div>
          </div>

          {/* Slide content mockup */}
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div className="space-y-2">
              {['Renewable innovation', 'Carbon capture tech', 'Smart grid systems'].map((item, i) => (
                <div key={i} className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-accent-primary flex-shrink-0" />
                  <div className="text-xs text-dark-text-muted">{item}</div>
                </div>
              ))}
            </div>
            <div className="bg-dark-bg-elevated rounded-component p-3">
              {/* Fake chart */}
              <div className="flex items-end gap-1 h-12">
                {[40, 65, 45, 80, 70, 90, 75].map((h, i) => (
                  <div
                    key={i}
                    className="flex-1 bg-accent-primary/60 rounded-sm"
                    style={{ height: `${h}%` }}
                  />
                ))}
              </div>
              <div className="text-2xs text-dark-text-muted mt-1 text-center">Growth 2020–2026</div>
            </div>
          </div>

          {/* Slide footer */}
          <div className="flex items-center justify-between border-t border-dark-text-muted/10 pt-3">
            <div className="flex gap-2">
              {['Dark Tech', '10 slides'].map((tag, i) => (
                <span key={i} className={`text-xs px-2 py-0.5 rounded-full ${i === 0 ? 'bg-accent-primary/20 text-accent-primary' : 'bg-dark-bg-elevated text-dark-text-muted'}`}>
                  {tag}
                </span>
              ))}
            </div>
            <div className="text-2xs text-dark-text-muted">2 / 10</div>
          </div>
        </div>
      </motion.div>
    </div>
  )
}

export default function Hero() {
  return (
    <section className="relative min-h-screen flex flex-col items-center justify-center pt-16 pb-12 overflow-hidden">
      {/* Subtle radial glow */}
      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-accent-primary/8 dark:bg-accent-primary/12 rounded-full blur-3xl pointer-events-none" />

      <div className="relative w-full px-6 sm:px-10 lg:px-16 w-full">
        <motion.div
          variants={stagger}
          initial="hidden"
          animate="visible"
          className="flex flex-col items-center text-center"
        >
          {/* Badge */}
          <motion.div variants={fadeUp}>
            <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent-subtle-light dark:bg-accent-subtle-dark border border-accent-primary/20 text-accent-primary text-xs font-medium mb-8">
              <span className="w-1.5 h-1.5 rounded-full bg-accent-primary animate-pulse" />
              AI-Powered Presentations
            </span>
          </motion.div>

          {/* Headline */}
          <motion.h1
            variants={fadeUp}
            className="text-4xl sm:text-5xl lg:text-hero font-medium text-light-text-primary dark:text-dark-text-primary leading-tight max-w-3xl mb-6"
            style={{ lineHeight: 1.15 }}
          >
            Create Stunning Decks,
            <br />
            <span className="text-accent-primary">Powered by Intelligence.</span>
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            variants={fadeUp}
            className="text-lg text-light-text-muted dark:text-dark-text-muted max-w-xl mb-8 leading-relaxed"
          >
            Pick a topic. Choose a theme. DeckIQ researches, designs, and builds
            your presentation — in seconds.
          </motion.p>

          {/* CTAs */}
          <motion.div variants={fadeUp} className="flex flex-col sm:flex-row items-center gap-3 mb-4">
            <Link
              href="/signup"
              className="bg-accent-primary hover:bg-indigo-600 text-white font-medium py-3 px-7 rounded-component transition-colors duration-150 text-sm whitespace-nowrap"
            >
              Generate Your First Deck →
            </Link>
            <a
              href="#how-it-works"
              onClick={(e) => {
                e.preventDefault()
                document.querySelector('#how-it-works')?.scrollIntoView({ behavior: 'smooth' })
              }}
              className="border border-light-text-muted/30 dark:border-dark-text-muted/30 hover:bg-light-bg-elevated dark:hover:bg-dark-bg-elevated text-light-text-primary dark:text-dark-text-primary py-3 px-7 rounded-component transition-colors duration-150 text-sm whitespace-nowrap"
            >
              See How It Works
            </a>
          </motion.div>

          {/* Subtext */}
          <motion.p variants={fadeUp} className="text-xs text-light-text-muted dark:text-dark-text-muted mb-16">
            3 free generations. No credit card required.
          </motion.p>

          {/* Mockup */}
          <motion.div variants={fadeUp} className="w-full max-w-xl">
            <SlidePreview />
          </motion.div>
        </motion.div>
      </div>
    </section>
  )
}


