import { NextResponse } from 'next/server'
import prisma from '@/lib/prisma'
import { verifyAccessToken, extractBearerToken } from '@/lib/auth'
import { supabaseAdmin } from '@/lib/supabase'
import PptxGenJS from 'pptxgenjs'

// Theme color mapping
const THEME_CONFIGS = {
  dark_tech: { bg: '0F0F14', text: 'FFFFFF', accent: '5B4CF5', font: 'Courier New' },
  minimal_light: { bg: 'F7F7FF', text: '0F0F14', accent: '5B4CF5', font: 'Arial' },
  corporate_blue: { bg: '1A2744', text: 'FFFFFF', accent: '3B82F6', font: 'Arial' },
  vibrant_creative: { bg: 'FF6B6B', text: 'FFFFFF', accent: 'FFE66D', font: 'Georgia' },
  nature_green: { bg: '1A3A2A', text: 'E8F5E9', accent: '66BB6A', font: 'Arial' },
  berlin: { bg: '1C1C1E', text: 'F2F2F7', accent: 'FF9500', font: 'Helvetica' },
  slate_dark: { bg: '1E293B', text: 'F8FAFC', accent: '94A3B8', font: 'Arial' },
  coral_energy: { bg: 'FF4500', text: 'FFFFFF', accent: 'FFD700', font: 'Arial' },
  midnight: { bg: '0D1117', text: 'C9D1D9', accent: '58A6FF', font: 'Courier New' },
  arctic: { bg: 'EFF6FF', text: '1E3A5F', accent: '2563EB', font: 'Arial' },
  terracotta: { bg: 'C46B40', text: 'FFF8F0', accent: 'E8B89A', font: 'Georgia' },
  ocean_depths: { bg: '003049', text: 'FCBF49', accent: 'EAE2B7', font: 'Arial' },
  sakura: { bg: 'FFF0F3', text: 'FF4D6D', accent: 'FF758C', font: 'Georgia' },
  desert_sand: { bg: 'D9B99B', text: '4A3728', accent: 'C75000', font: 'Arial' },
  emerald: { bg: '064E3B', text: 'ECFDF5', accent: '10B981', font: 'Arial' },
  neon_noir: { bg: '09090B', text: 'E4E4E7', accent: 'A855F7', font: 'Courier New' },
  pastel_dream: { bg: 'FFF1FB', text: '6B21A8', accent: 'EC4899', font: 'Georgia' },
  urban_grey: { bg: '3F3F46', text: 'FAFAFA', accent: 'A1A1AA', font: 'Helvetica' },
  golden_hour: { bg: '78350F', text: 'FEF3C7', accent: 'F59E0B', font: 'Georgia' },
  auto: { bg: '0F0F14', text: 'FFFFFF', accent: '5B4CF5', font: 'Arial' },
}

function generateSlides(topic, slideCount, theme) {
  const tc = THEME_CONFIGS[theme] || THEME_CONFIGS.auto
  const pptx = new PptxGenJS()

  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'DeckIQ'
  pptx.company = 'DeckIQ'
  pptx.title = topic

  // Title slide
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: tc.bg }
  titleSlide.addText(topic, {
    x: 0.5, y: 1.5, w: 9, h: 1.5,
    fontSize: 36, bold: true, color: tc.text,
    fontFace: tc.font, align: 'center',
  })
  titleSlide.addText('Generated by DeckIQ', {
    x: 0.5, y: 3.2, w: 9, h: 0.5,
    fontSize: 14, color: tc.accent,
    fontFace: tc.font, align: 'center',
  })

  // Content slides
  const samplePoints = [
    ['Introduction', ['Overview of the topic', 'Why this matters', 'Key concepts']],
    ['Core Concepts', ['Fundamental principles', 'Key terminology', 'Framework overview']],
    ['Analysis', ['Deep dive into data', 'Patterns and trends', 'Critical insights']],
    ['Key Points', ['Main takeaways', 'Supporting evidence', 'Real-world examples']],
    ['Challenges', ['Common obstacles', 'Risk factors', 'Mitigation strategies']],
    ['Solutions', ['Recommended approaches', 'Best practices', 'Implementation steps']],
    ['Case Studies', ['Real-world applications', 'Success stories', 'Lessons learned']],
    ['Future Outlook', ['Emerging trends', 'Predictions', 'Opportunities ahead']],
    ['Action Plan', ['Next steps', 'Timeline', 'Key stakeholders']],
    ['Resources', ['Further reading', 'Tools and references', 'Contact information']],
    ['Q&A', ['Open discussion', 'Feedback welcome', 'Next meeting: TBD']],
    ['Summary', ['Key accomplishments', 'Progress made', 'Next milestones']],
    ['Conclusion', ['Summary of key points', 'Final thoughts', 'Thank you']],
    ['Appendix', ['Supporting data', 'Detailed analysis', 'Technical notes']],
    ['Thank You', ['Questions welcome', 'Connect with us', 'Stay in touch']],
  ]

  for (let i = 1; i < slideCount; i++) {
    const [title, bullets] = samplePoints[i % samplePoints.length]
    const slide = pptx.addSlide()
    slide.background = { color: tc.bg }

    // Slide number accent bar
    slide.addShape('rect', {
      x: 0, y: 0, w: 0.06, h: 5.63,
      fill: { color: tc.accent },
    })

    slide.addText(title, {
      x: 0.4, y: 0.3, w: 9.2, h: 0.8,
      fontSize: 22, bold: true, color: tc.text,
      fontFace: tc.font,
    })

    slide.addText(bullets.map(b => `• ${b}`).join('\n'), {
      x: 0.4, y: 1.3, w: 9.2, h: 3.5,
      fontSize: 14, color: tc.text,
      fontFace: tc.font, valign: 'top',
    })

    // Slide number
    slide.addText(`${i + 1}`, {
      x: 9.1, y: 5.1, w: 0.6, h: 0.3,
      fontSize: 10, color: tc.accent,
      fontFace: tc.font, align: 'right',
    })
  }

  return pptx
}

function sendEvent(controller, data) {
  controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify(data)}\n\n`))
}

export async function POST(request) {
  const token = extractBearerToken(request)
  if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  let payload
  try {
    payload = verifyAccessToken(token)
  } catch {
    return NextResponse.json({ error: 'Invalid token' }, { status: 401 })
  }

  const { topic, slideCount = 7, theme = 'auto' } = await request.json()
  if (!topic?.trim()) {
    return NextResponse.json({ error: 'Topic is required' }, { status: 400 })
  }

  const userId = payload.userId

  const stream = new ReadableStream({
    async start(controller) {
      try {
        // Check credits
        const user = await prisma.user.findUnique({ where: { id: userId } })
        if (!user || user.credits <= 0) {
          sendEvent(controller, { step: 'error', message: 'No credits remaining.' })
          controller.close()
          return
        }

        // Deduct credit optimistically
        await prisma.user.update({ where: { id: userId }, data: { credits: { decrement: 1 } } })

        sendEvent(controller, { step: 1, message: 'Planning slides...' })
        await new Promise((r) => setTimeout(r, 800))

        sendEvent(controller, { step: 2, message: 'Researching content...' })
        await new Promise((r) => setTimeout(r, 1200))

        sendEvent(controller, { step: 3, message: 'Adding images...' })
        await new Promise((r) => setTimeout(r, 800))

        sendEvent(controller, { step: 4, message: 'Saving your deck...' })

        // Generate PPTX
        const pptx = generateSlides(topic, slideCount, theme)
        const buffer = await pptx.write({ outputType: 'nodebuffer' })
        const filename = `${userId}/${Date.now()}-${topic.slice(0, 30).replace(/[^a-z0-9]/gi, '_')}.pptx`

        // Upload to Supabase Storage
        const { data: uploadData, error: uploadError } = await supabaseAdmin.storage
          .from('ppts')
          .upload(filename, buffer, { contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' })

        if (uploadError) throw uploadError

        const { data: { publicUrl } } = supabaseAdmin.storage.from('ppts').getPublicUrl(filename)

        // Save to DB
        const ppt = await prisma.pPT.create({
          data: { userId, title: topic, theme, slideCount, fileUrl: publicUrl },
        })

        sendEvent(controller, { step: 'done', fileUrl: publicUrl, pptId: ppt.id, title: topic })
      } catch (err) {
        console.error('[generate]', err)
        // Restore credit on failure
        try {
          await prisma.user.update({ where: { id: userId }, data: { credits: { increment: 1 } } })
        } catch {}
        sendEvent(controller, { step: 'error', message: 'Generation failed. Credit restored.' })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
    },
  })
}

