import Link from 'next/link'
import Footer from '@/components/LandingPage/Footer'
import ThemeToggle from '@/components/shared/ThemeToggle'

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-light-bg-primary dark:bg-dark-bg-primary flex flex-col">
      {/* Simple Header */}
      <header className="w-full px-6 sm:px-10 lg:px-16 h-16 flex items-center justify-between border-b border-light-text-muted/10 dark:border-dark-text-muted/10">
        <Link href="/" className="flex items-center gap-2 text-xl font-medium text-light-text-primary dark:text-dark-text-primary">
          Deck<span className="text-accent-primary">IQ</span>
        </Link>
        <div className="flex items-center gap-4">
          <ThemeToggle />
          <Link href="/" className="text-sm font-medium text-light-text-muted dark:text-dark-text-muted hover:text-light-text-primary dark:hover:text-dark-text-primary transition-colors">
            Back to Home
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 w-full max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-light-text-primary dark:text-dark-text-primary mb-2">Terms & Conditions</h1>
        <p className="text-sm text-light-text-muted dark:text-dark-text-muted mb-8">Last updated: June 2025</p>

        <div className="space-y-8 text-light-text-primary dark:text-dark-text-primary">
          
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-sm text-light-text-muted dark:text-dark-text-muted leading-relaxed mb-4">
              By accessing and using DeckIQ, you agree to be bound by these Terms & Conditions. If you disagree with any part of the terms, then you may not access the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Service Usage</h2>
            <p className="text-sm text-light-text-muted dark:text-dark-text-muted leading-relaxed mb-3">
              When registering or using our platform, you agree to the following guidelines:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm text-light-text-muted dark:text-dark-text-muted">
              <li>You must provide accurate and complete account information.</li>
              <li>You are responsible for safeguarding the password that you use to access the service.</li>
              <li>You may not use the AI system to generate harmful, illicit, or hateful content.</li>
              <li>You may not reverse-engineer, scrape, or programmatically abuse the generation endpoints.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Subscriptions & Credits</h2>
            <p className="text-sm text-light-text-muted dark:text-dark-text-muted leading-relaxed">
              DeckIQ operates on a credit-based system. Credits are consumed upon successful presentation generation. For detailed information regarding our non-refundable policy on credits, please review our entirely separate <Link href="/refund" className="text-accent-primary hover:underline">Refund Policy</Link> page.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Disclaimer & Liability</h2>
            <p className="text-sm text-light-text-muted dark:text-dark-text-muted leading-relaxed">
              The presentations and content generated by DeckIQ are provided "as is" and without warranties of any kind. We do not guarantee that the AI-generated facts will be 100% accurate, and it is the user's responsibility to review and edit the generated slides.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Contact Information</h2>
            <p className="text-sm text-light-text-muted dark:text-dark-text-muted leading-relaxed">
              For any questions regarding these Terms & Conditions, please contact us at: <br/>
              Email: <a href="mailto:deckiqteam@gmail.com" className="text-accent-primary hover:underline">deckiqteam@gmail.com</a>
            </p>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  )
}
